# .github/workflows/manual_run.yml

name: Run abcd.py Manually

# This allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # Fetches your code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers and dependencies
      run: playwright install --with-deps # Installs browsers (like Chromium) and OS dependencies

    - name: Run Python script
      run: python abcd.py # Execute your script
